version: '3'

services:
  mongo_db:
    container_name: mongo_db
    image: mongo:6.0.15
    restart: unless-stopped
    volumes:
      - '.private/mongo_data:/var/lib/mongodb'
    ports:
      - 27017:27017

  api:
    build: ./backend/.
    ports:
      - 3000:3000
    environment:
      

    depends_on:
      - mongo_db

volumes:
  mongo_db: {}