version: '3.9'
services:

  backend:
    image: backend:1.0.0
    container_name: ${SERVER_HOST}
    build: 
      context: ./backend
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - ./backend:/backend
      - backend-v:/backend
    depends_on:
      - database
  
  database:
    image: database:1.0.0
    container_name: ${DATABASE_HOST}
    build: 
      context: ./database
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    volumes:
      - database-v:/data/db

volumes:
  backend-v:
    name: "backend-v"
  database-v:
    name: "database-v"